/*
__author__ = 'Shuang Su'
__copyright__ = 'Copyright 2018, Shuang Su'
__version__ = '0.1'
__email__ = 'shuangs@andrew.cmu.edu'
*/
require('./contractAddress.js');
require('./connect.js');
const fs = require('fs');
var buffer=fs.readFileSync("data.txt");
var stringData=buffer.toString('ascii');
transactionData=stringData.split('\n');
console.log(transactionData.length);
function sleep(miliseconds) {
   var currentTime = new Date().getTime();
   while (currentTime + miliseconds >= new Date().getTime()) {
   }
}

 for(i=0;i<transactionData.length;i++){
input=transactionData[i].split(' ');
sender=input.pop();
if(sender=='1')
{
web31.eth.defaultAccount=web31.eth.coinbase;
if(input[2]=='1')
transactionSearch1.setProduceProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]),parseInt(input[6]),parseInt(input[7]),parseInt(input[8]));
else
transactionSearch1.setProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]));
}
if(sender=='2')
{
web32.eth.defaultAccount=web32.eth.coinbase;
if(input[2]=='1')
transactionSearch2.setProduceProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]),parseInt(input[6]),parseInt(input[7]),parseInt(input[8]));
else
transactionSearch2.setProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]));
}
if(sender=='3')
{
 web33.eth.defaultAccount=web33.eth.coinbase;
if(input[2]=='1')
transactionSearch3.setProduceProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]),parseInt(input[6]),parseInt(input[7]),parseInt(input[8]));
else
transactionSearch3.setProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]));
}
if(sender=='4')
{
web34.eth.defaultAccount=web34.eth.coinbase;
if(input[2]=='1')
transactionSearch4.setProduceProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]),parseInt(input[6]),parseInt(input[7]),parseInt(input[8]));
else
transactionSearch4.setProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]));
}
if(sender=='5')
{
web35.eth.defaultAccount=web35.eth.coinbase;
if(input[2]=='1')
transactionSearch5.setProduceProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]),parseInt(input[6]),parseInt(input[7]),parseInt(input[8]));
else
transactionSearch5.setProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]));
}
if(sender=='6')
{
web36.eth.defaultAccount=web36.eth.coinbase;
if(input[2]=='1')
transactionSearch6.setProduceProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]),parseInt(input[6]),parseInt(input[7]),parseInt(input[8]));
else
transactionSearch6.setProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]));
}
if(sender=='7')
{
web37.eth.defaultAccount=web37.eth.coinbase;
if(input[2]=='1')
transactionSearch7.setProduceProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]),parseInt(input[6]),parseInt(input[7]),parseInt(input[8]));
else
transactionSearch7.setProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]));
}
if(sender=='8')
{
web38.eth.defaultAccount=web38.eth.coinbase;
if(input[2]=='1')
transactionSearch8.setProduceProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]),parseInt(input[6]),parseInt(input[7]),parseInt(input[8]));
else
transactionSearch8.setProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]));
}
if(sender=='9')
{
web39.eth.defaultAccount=web39.eth.coinbase;
if(input[2]=='1')
transactionSearch9.setProduceProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]),parseInt(input[6]),parseInt(input[7]),parseInt(input[8]));
else
transactionSearch9.setProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]));
}
if(sender=='10')
{
web310.eth.defaultAccount=web310.eth.coinbase;
if(input[2]=='1')
transactionSearch10.setProduceProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]),parseInt(input[6]),parseInt(input[7]),parseInt(input[8]));
else
transactionSearch10.setProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]));
}
if(sender=='11')
{
web311.eth.defaultAccount=web311.eth.coinbase;
if(input[2]=='1')
transactionSearch11.setProduceProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]),parseInt(input[6]),parseInt(input[7]),parseInt(input[8]));
else
transactionSearch11.setProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]));
}
if(sender=='12')
{
web312.eth.defaultAccount=web312.eth.coinbase;
if(input[2]=='1')
transactionSearch12.setProduceProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]),parseInt(input[6]),parseInt(input[7]),parseInt(input[8]));
else
transactionSearch12.setProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]));
}
if(sender=='13')
{
web313.eth.defaultAccount=web313.eth.coinbase;
if(input[2]=='1')
transactionSearch13.setProduceProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]),parseInt(input[6]),parseInt(input[7]),parseInt(input[8]));
else
transactionSearch13.setProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]));
}
if(sender=='14')
{
web314.eth.defaultAccount=web314.eth.coinbase;
if(input[2]=='14')
transactionSearch14.setProduceProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]),parseInt(input[6]),parseInt(input[7]),parseInt(input[8]));
else
transactionSearch14.setProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]));
}
if(sender=='15')
{
web315.eth.defaultAccount=web315.eth.coinbase;
if(input[2]=='15')
transactionSearch15.setProduceProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]),parseInt(input[6]),parseInt(input[7]),parseInt(input[8]));
else
transactionSearch15.setProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]));
}
if(sender=='16')
{
web316.eth.defaultAccount=web316.eth.coinbase;
if(input[2]=='1')
transactionSearch16.setProduceProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]),parseInt(input[6]),parseInt(input[7]),parseInt(input[8]));
else
transactionSearch16.setProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]));
}
if(sender=='17')
{
web317.eth.defaultAccount=web317.eth.coinbase;
if(input[2]=='1')
transactionSearch17.setProduceProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]),parseInt(input[6]),parseInt(input[7]),parseInt(input[8]));
else
transactionSearch17.setProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]));
}
if(sender=='18')
{
web318.eth.defaultAccount=web318.eth.coinbase;
if(input[2]=='1')
transactionSearch18.setProduceProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]),parseInt(input[6]),parseInt(input[7]),parseInt(input[8]));
else
transactionSearch18.setProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]));
}
if(sender=='19')
{
web319.eth.defaultAccount=web319.eth.coinbase;
if(input[2]=='1')
transactionSearch19.setProduceProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]),parseInt(input[6]),parseInt(input[7]),parseInt(input[8]));
else
transactionSearch19.setProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]));
}
if(sender=='20')
{
web320.eth.defaultAccount=web320.eth.coinbase;
if(input[2]=='1')
transactionSearch20.setProduceProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]),parseInt(input[6]),parseInt(input[7]),parseInt(input[8]));
else
transactionSearch20.setProductInfo(parseInt(input[0]),parseInt(input[1]),parseInt(input[2]),parseInt(input[3]),parseInt(input[4]),parseInt(input[5]));
}

console.log("Data:%s",input);
sleep(20000);
 }
